# Generated by Django 5.0.1 on 2024-03-29 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 11, 29, 30, 895701, tzinfo=datetime.timezone.utc)),
        ),
    ]
